general:
  #input_mesh_directory: /scratch/bayer/Dat_inputs/Wuerfel.dat
  input_mesh_directory: /scratch/bayer/Git_respository/img2physiprop/Test_dat/inputfile_tutorial.dat
  #input_mesh_directory: /scratch/bayer/01_ComputationalAnalysisAAA/Wuerfel/Wuerfelmesh.mesh
  input_data_directory: /scratch/bayer/DICOM_Inputs/Human/
  #input_data_directory: "/scratch/bayer/Git_respository/img2physiprop/Test_png/"
  output_directory: output
  user_script: /scratch/bayer/user_functions/user_function.py
  user_function: user_function
  sim_name: test_sim
Further customizations:
  #Smoothing
  Smoothing: False #defaut: False. (True: Smoothin active, False: No Smoothin)
  Smoothing_area: 27 #default: 27 (Takes mean value of n voxels around each voxel to compensate measurement errors)
  #calculation_type:
  # nodes: mean of element-nodes
  # elementcenter: value of element-center
  # allVoxel: mean of all Voxel inside the Mesh
  calculation_type: nodes
#Needed information for PNG-Image-data
Additional Information:
  Pixel_Spacing: [1, 1] #default: [1,1]
  Slice_Thickness: 1 #default: 1
  Image_Position: [0, 0, 0] #default: [0,0,0]
  Image_Orientation: [0, 1, 0, 1, 0, 0] #default: [0,1,0,1,0,0]
