repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [— maxkb=1000]
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: debug-statements
      - id: no-commit-to-branch # prevent commiting to main/master
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-r", "-ll", "src/i2pp/", "tests/"]
        additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
        args: ["--line-length=79"]
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        language: python
        args: ["--in-place", "--config=./pyproject.toml", "-r", "src/i2pp/", "tests/"]
  - repo: https://github.com/kplaube/pre-commit-dodgy
    rev: 0.0.2
    hooks:
      - id: dodgy
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        args: [--fail-under=100, --ignore-init-module, --style=google, -vv, src/i2pp/, tests/]
  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "79", "--filter-files", "--src", "[src/i2pp/, tests/]"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: ["--install-types", "--non-interactive", "--ignore-missing-imports", "--follow-imports=silent"]
  - repo: https://github.com/asmeurer/removestar
    rev: "1.5.2"
    hooks:
      - id: removestar
  - repo: https://github.com/pamoller/xmlformatter
    rev: v0.2.8
    hooks:
      - id: xml-formatter
        args: [--indent, "2", --indent-char, " ", --selfclose, --overwrite, --eof-newline]
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
